name: placeholder
description: "A new Flutter project."
publish_to: "none"
version: 0.2.2+5

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.19.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  gap: ^3.0.1
  pocketbase: ^0.22.0
  supabase_flutter: ^2.8.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - staging.env
    - prod.env
