name: placeholder
description: "A new Flutter project."
publish_to: "none"
version: 0.12.0+38

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  gap: ^3.0.1
  pocketbase: ^0.22.0
  uuid: ^4.5.1
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  sentry_flutter: ^8.14.2
  flutter_slidable: ^4.0.0
  url_launcher: ^6.3.1
  material_symbols_icons: ^4.2815.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  http: ^1.4.0
  package_info_plus: ^8.3.0
  hydrated_bloc: ^10.0.0
  supabase_flutter: ^2.9.1
  simple_shadow: ^0.3.1
  toastification: ^3.0.3
  path: ^1.9.1
  foundation: ^0.0.5
  flutter_animate: ^4.5.2
  lottie: ^3.3.1
  cached_network_image: ^3.4.1
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - staging.env
    - prod.env
