name: placeholder
description: "A new Flutter project."
publish_to: "none"
version: 0.7.0+22

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  gap: ^3.0.1
  pocketbase: ^0.22.0
  supabase_flutter: ^2.8.4
  uuid: ^4.5.1
  flutter_secure_storage: ^9.2.4
  purchases_flutter: ^8.7.3
  intl: ^0.20.2
  sentry_flutter: ^8.14.2
  flutter_slidable: ^4.0.0
  url_launcher: ^6.3.1
  material_symbols_icons: ^4.2815.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - staging.env
    - prod.env
